<a href="https://colab.research.google.com/github/RKohls21/CPSC-419/blob/main/Intro_to_419.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
miles = 1875
gallons = 97
mpg = miles/gallons
print(mpg)

19.329896907216494


In [4]:
import numpy as np
bodhi = np.array([1, 2, 3])

In [5]:
bodhi

array([1, 2, 3])

In [6]:
arr2d = np.array([[1, 2, 3], [4, 5, 6]])

In [7]:
arr2d

array([[1, 2, 3],
       [4, 5, 6]])

In [8]:
import numpy
arr3 = numpy.array ([1, 2, 3])

In [9]:
import numpy as deeplearninglibrary
arr4 = deeplearninglibrary.array([1, 2, 3])

Other ways to write arrays


In [10]:
pArr = [x for x in range (10)]

In [11]:
pArr

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [12]:
pArr2d = [[x + y * 10 for x in range(10) ] for y in range(10)]

In [13]:
pArr2d

[[0, 1, 2, 3, 4, 5, 6, 7, 8, 9],
 [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
 [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
 [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
 [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
 [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
 [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
 [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
 [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
 [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]]

#### In Numpy

In [14]:
nArr = np.arange(100)

In [15]:
nArr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [20]:
nArr2 = nArr.reshape((10,10))

In [21]:
nArr[3]

3

In [22]:
nArr2[1][3]

13

In [23]:
nArr2

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

## All the same stuff as python - why bother?

## Speed

In [24]:
%time pyT1 = [[x + y * 1000 for x in range (1000)] for y in range (1000)]

CPU times: user 114 ms, sys: 35.2 ms, total: 149 ms
Wall time: 149 ms


In [26]:
%time nuT1 = np.arange(1000000).reshape(1000,1000)

CPU times: user 3.39 ms, sys: 0 ns, total: 3.39 ms
Wall time: 3.02 ms


## Add 1 to each element, Python first

In [30]:
def add1():
  for i in range(1000):
    for j in range (1000):
      pyT1[i][j] = pyT1[i][j] + 1
%time add1()

CPU times: user 130 ms, sys: 1.97 ms, total: 132 ms
Wall time: 134 ms


In [31]:
%time nuT1 + 1

CPU times: user 3.92 ms, sys: 55 µs, total: 3.97 ms
Wall time: 3.08 ms


array([[      1,       2,       3, ...,     998,     999,    1000],
       [   1001,    1002,    1003, ...,    1998,    1999,    2000],
       [   2001,    2002,    2003, ...,    2998,    2999,    3000],
       ...,
       [ 997001,  997002,  997003, ...,  997998,  997999,  998000],
       [ 998001,  998002,  998003, ...,  998998,  998999,  999000],
       [ 999001,  999002,  999003, ...,  999998,  999999, 1000000]])

## Numpy Functions

In [33]:
nuT1.mean()

499999.5

In [34]:
nuT1.sum()

499999500000